# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: github-pages

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          cache: 'pip'
      - run: pip install firebase_admin
      - run: pip install numpy
      - run: pip install matplotlib 
      - run: pip install selenium
      - run: pip install chromedriver_binary
      - run: pip install seaborn
      - run: pip install bokeh
      - run: pip install IPython
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        env:
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        with:
          files: 'mumble-melody-longitudinal-firebase-adminsdk-34x0r-52f98ad6f0.json'
      - run: python -m json.tool mumble-melody-longitudinal-firebase-adminsdk-34x0r-52f98ad6f0.json
      - name: Run script
        env:
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: python continuousplots_MumbleMelody.py

